FROM ducksouplab/debian-gstreamer:deb12-with-plugins-cuda12.2-gst1.28.0

# TensorRT is already present in the base image ducksouplab/debian-gstreamer
# so we don't need to reinstall it. Just ensure ldconfig runs for the new libs.

COPY --from=mp_plugins_gpu /lib/libmp_runtime.so /usr/local/lib/
COPY --from=mp_plugins_gpu /plugins/*.so /usr/local/lib/gstreamer-1.0/

ENV GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0:/opt/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
ENV LD_LIBRARY_PATH=/usr/local/lib:/opt/gstreamer/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
ENV PATH=/opt/gstreamer/bin:$PATH

RUN ldconfig
